### ISSUE TITLE
Number of Severities?

### ISSUE THREAD

**Issue by ChengJiacheng** [Jason-Qiu/MM_Robustness#1]
Hi, Thanks for your work! I am interested in evaluating my multi-modal model on this benchmark but have a question.
In your paper, it is mentioned that there are 5 Severities for most text perturbations. But in `perturb_COCO_TP.py`, I see most perturbation have 7 Severities (e.g., char_rate_chunk = [1,2,3,4,5,6,7]). I wonder which 5 of them should I use in the final evaluation? [1,2,3,4,5] or [3,4,5,6,7]?

**Comment by Jielin-Qiu** [comment]
Hi Jiacheng, thanks for your interest in our work. In our results in the paper, we used the parameter set [3,4,5,6,7].

**Comment by ChengJiacheng** [comment]
@Jason-Qiu Thank you for the quick reply, Jason! 
I notice that the generation of COCO-TP and FLICKR-TP using the Python scripts is stochastic. I am not sure if my generated data are exactly the same as the one used in the paper. Just want to make the evaluation in my work fair, I wonder if you could kindly send me (jicheng@eng.ucsd.edu) a copy of the COCO-TP and FLICKR-TP annotation json files? Your help is greatly appreciated!

**Comment by Jielin-Qiu** [comment]
Hi Jiacheng, there is a seed provided in the scripts to control the generated perturbations, so your generated ones should be the same as ours.
