### ISSUE TITLE
Any link to the purturbed datasets?

### ISSUE THREAD

**Issue by chengyuehuang511** [Jason-Qiu/MM_Robustness#2]
Is it possible that you provide the purturbed dataset directly? It will save a lot of time preprocessing the original data. Thanks a lot for your help!

**Comment by Jielin-Qiu** [comment]
Hi Chengyue, thanks for your interest in our work. Unfortunately, we do not own the copyright of those datasets, so we are not able to distribute them directly. Please follow the notes in each folder, it should be very easy and straightforward to duplicate the results.
